[REQ-duplicate]
partof = "REQ-purpose-learning"
text = '''
duplicates **shall not** be allowed, as they would be extremely confusing
'''

[RSK-load]
partof = "REQ-load"
text = '''
A user could give invalid data. Input data must be checked
for validity and an error must be raised if invalid.
'''

[SPC-load-format]
partof = "REQ-purpose-config"
text = '''
The format of the csv file **shall** be a csv file of the form:
```
City, Capitol
```

Where whitespace is ignored
'''

[SPC-load-validate]
partof = "REQ-duplicate, SPC-load-format"
text = '''
input questions **shall** be validated to meet the
linked requirements, printing and returning an error
if they are not met.
'''

[SPC-question]
text = '''
The `Question` class **shall** be the primary datatype used for questions
in the application. Quetions shall:
 - store the question and answer
 - provide a method `ask` to ask the user the question
	and validate the answer
'''

[TST-load]
partof = "RSK-load"
text = '''
There **will** be plaintext tests related to loading the questions.

> Note: this is automatically linked to SPC-load,
> but RSK links must be explicit
'''

[TST-load-csv]
partof = "SPC-load-format"
text = '''
There **will** be tests that validate that a simple csv 
file load works.
'''

[TST-load-unit]
partof = "SPC-load-validate"
text = '''
At least the following unit tests **will** be implemented:
- test invalid number of columns
- test duplicate names
'''
